[theme]
base = "dark"
primaryColor = "#10B7C4"
backgroundColor = "#DCEBFA"
secondaryBackgroundColor = "#10213B"
textColor = "#123154"
font = "sans serif"

[server]
headless = true
runOnSave = true
maxUploadSize = 200

[browser]
gatherUsageStats = false
